# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71a052d79b7db96068a8284a02b09b21"
name = "Order-export"
application_url = "https://remix-orders-export.onrender.com"
embedded = true
handle = "order-export-59"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://example.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://example.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_draft_orders,read_fulfillments,read_merchant_managed_fulfillment_orders,read_orders,read_products,write_assigned_fulfillment_orders,write_customers,write_draft_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products"

[auth]
redirect_urls = ["https://remix-orders-export.onrender.com/auth/callback", "https://remix-orders-export.onrender.com/auth/shopify/callback", "https://remix-orders-export.onrender.com/api/auth/callback"]

[pos]
embedded = false
